import React, { useState, useMemo } from 'react';
import { Header } from './components/Header';
import { DishCard } from './components/DishCard';
import { RecipeModal } from './components/RecipeModal';
import { DISHES } from './constants';
import { Dish, Category } from './types';

const CATEGORIES: Category[] = ['All', 'Breakfast', 'Mains', 'Sides', 'Drinks'];

const App: React.FC = () => {
  const [selectedDish, setSelectedDish] = useState<Dish | null>(null);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [activeCategory, setActiveCategory] = useState<Category>('All');

  const handleDishClick = (dish: Dish) => {
    setSelectedDish(dish);
    setIsModalOpen(true);
  };

  const handleCloseModal = () => {
    setIsModalOpen(false);
    // Small delay to allow animation to finish before clearing data if we added exit animations
    setTimeout(() => setSelectedDish(null), 300);
  };

  const filteredDishes = useMemo(() => {
    if (activeCategory === 'All') return DISHES;
    return DISHES.filter(dish => dish.category === activeCategory);
  }, [activeCategory]);

  return (
    <div className="min-h-screen flex flex-col bg-kenya-sand/30">
      <Header />

      <main className="flex-grow container mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="text-center mb-10">
          <h2 className="text-4xl md:text-5xl font-serif font-bold text-kenya-black mb-4">
            Taste of the <span className="text-kenya-red">Savanna</span>
          </h2>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Discover the vibrant, delicious world of Kenyan cuisine. 
            From hearty breakfast to nyama choma, experience it all with AI.
          </p>
        </div>

        {/* Category Filter */}
        <div className="flex flex-wrap justify-center gap-3 mb-12">
          {CATEGORIES.map((category) => (
            <button
              key={category}
              onClick={() => setActiveCategory(category)}
              className={`px-6 py-2 rounded-full text-sm font-semibold transition-all duration-300 transform hover:-translate-y-0.5 ${
                activeCategory === category
                  ? 'bg-kenya-red text-white shadow-md scale-105'
                  : 'bg-white text-gray-600 hover:bg-gray-100 border border-gray-200'
              }`}
            >
              {category}
            </button>
          ))}
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 lg:gap-12">
          {filteredDishes.map((dish) => (
            <DishCard 
              key={dish.item_name} 
              dish={dish} 
              onClick={handleDishClick} 
            />
          ))}
        </div>

        {filteredDishes.length === 0 && (
          <div className="text-center py-20 text-gray-500">
            No dishes found in this category.
          </div>
        )}
      </main>

      <footer className="bg-white border-t border-gray-200 mt-auto">
        <div className="max-w-7xl mx-auto py-8 px-4 sm:px-6 lg:px-8 flex flex-col md:flex-row justify-between items-center">
          <p className="text-gray-500 text-sm">
            &copy; {new Date().getFullYear()} Sawa Flavors. Powered by Google Gemini.
          </p>
          <div className="mt-4 md:mt-0 flex space-x-6 text-gray-400">
            <span className="text-xs">Images generated by Imagen 4 | Recipes by Gemini 2.5 Flash</span>
          </div>
        </div>
      </footer>

      {selectedDish && (
        <RecipeModal 
          dish={selectedDish} 
          isOpen={isModalOpen} 
          onClose={handleCloseModal} 
        />
      )}
    </div>
  );
};

export default App;